services:
  db:
    image: postgres:16-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: $Secad03
    volumes:
      - pgdata:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
volumes:
  pgdata: